export const metadata = {
  title: { default: ' About|My Media Shop', Template: '%s | My Media Shop' },
  description: 'Generated by create next app',
};
export default function About() {
  return <div>About</div>;
}
