export const metadata = {
  title: { default: ' Products|My Media Shop', Template: '%s | My Media Shop' },
  description: 'Generated by create next app',
};
export default function Products() {
  return <div>Products</div>;
}
