import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import { getProducts } from '../../database/products';

export const metadata = {
  title: { default: ' Products|My Media Shop', Template: '%s | My Media Shop' },
  description: 'Generated by create next app',
};

export default function Products() {
  const products = getProducts();
  return (
    <div>
      <h1>My Products</h1>
      {products.map((product) => {
        return (
          <div key={`product-div-${product.id}`}>
            <Link href={`/products/${product.id}`}>{product.title}</Link>
            <Image
              src={`/images/${product.title}.jpg`}
              alt={product.title}
              width={200}
              height={200}
            />
          </div>
        );
      })}
    </div>
  );
}
